### ISSUE TITLE
Travis CI build and flutter test failing

### ISSUE THREAD

**Issue by ardacebi** [ardacebi/fasttake#22]
For some reason, the Travis CI build fails even if the Flutter build succeeds. 

The `flutter test` command also fails on a local installation so it's a problem with the Flutter project that **doesn't effect the project from building and working**.

## flutter test output

```
00:08 +0: Counter increments smoke test                                        
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building MyApp(dirty):
The getter 'delegate' was called on null.
Receiver: null
Tried calling: delegate

The relevant error-causing widget was:
  MyApp file:///Users/ardacebi/fasttake/test/widget_test.dart:16:29

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      MyApp.build (package:fasttake/main.dart:18:57)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
#10     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1006:5)
#11     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1020:7)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#14     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:974:18)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#18     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:872:9)
#21     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#22     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:859:27)
#23     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:323:22)
#26     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#27     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:320:27)
#28     main.<anonymous closure> (file:///Users/ardacebi/fasttake/test/widget_test.dart:16:18)
#29     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)
#30     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)
<asynchronous suspension>
#33     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)
#34     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)
#40     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)
#41     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)
#42     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)
<asynchronous suspension>
#43     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)
#48     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)
#49     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)
#54     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)
#55     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)
#69     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#70     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
(elided 32 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "0" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/ardacebi/fasttake/test/widget_test.dart:19:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)
#10     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)
#16     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)
#17     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)
#18     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)
<asynchronous suspension>
#19     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)
#24     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)
#25     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)
#30     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)
#31     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
(elided 28 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/ardacebi/fasttake/test/widget_test.dart line 19
The test description was:
  Counter increments smoke test
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:08 +0 -1: Counter increments smoke test [E]                                 
  Test failed. See exception logs above.
  The test description was: Counter increments smoke test
  
00:08 +0 -1: Some tests failed.        
```

**Comment by ardacebi** [comment]
Switched to codemagic, resolves issue.
